version: "3"
services: 
  chat_db:
    image: mysql:5.7
    container_name: chat_db
    restart: always
    command: [
      '--character-set-server=utf8mb4', #设置数据库表的数据集
      '--collation-server=utf8mb4_unicode_ci', #设置数据库表的数据集
    ]
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
  chat_be: 
    image: node:12.18.4
    container_name: chat_be
    working_dir: /home/node/app
    # command: npm config set registry https://registry.npm.taobao.org
    command: node dist/main.js
    volumes:
      - ./server:/home/node/app
    restart: always
    ports: 
      - 3305:3305
    depends_on:
       - chat_db
  chat_fe: 
    image: nginx:latest
    container_name: chat_fe
    restart: always
    ports: 
      - 8080:8080
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./client/build:/usr/share/nginx/html
